const eserler = [
    {
        "id": 1,
        "eser": "Gülşen-i Ezhar Açtı Her Yana - Basmacı Abdi Efendi - Mahur",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/gulsen-i-ezhar-acti-her-yana-basmaci-abdi-efendi-mahur.18885/"
    },
    {
        "id": 2,
        "eser": "Yollarda Kalan Gözlerimin Nurunu Yordum - Cavide Hayre Hanım - Karaosmanzade - Hüseyni Aşiran",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/yollarda-kalan-gozlerimin-nurunu-yordum-cavide-hayre-hanim-karaosmanzade-huseyni-asiran.38958/"
    },
    {
        "id": 3,
        "eser": "Ateş Gibi Bir Nehr Akıyordu ( Parilti) - Cavide Hayre Hanım - Karaosmanzade - Şehnaz Buselik",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/ates-gibi-bir-nehr-akiyordu-parilti-cavide-hayre-hanim-karaosmanzade-sehnaz-buselik.2876/"
    },
    {
        "id": 4,
        "eser": "Ağır Ağır Çıkacaksın Bu Merdivenlerden - Cavide Hayri Hanım (Karaosmanzade) - Şedaraban",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/agir-agir-cikacaksin-bu-merdivenlerden-cavide-hayri-hanim-karaosmanzade-sedaraban.399/"
    },
    {
        "id": 5,
        "eser": "Abdülkadir ya Kadir ya Geylani - Belirsiz - Hicaz-ı Acem, Hicaz-ı Türki, Hicaz-ı Uşşak",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/abdulkadir-ya-kadir-ya-geylani-belirsiz-hicaz-i-acem-hicaz-i-turki-hicaz-i-ussak.50/"
    },
    {
        "id": 6,
        "eser": "Ben Aşık-ı Mahzun u Perişanı Unutma - Kadri Efendi (Ama) - Nikriz",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/ben-asik-i-mahzun-u-perisani-unutma-kadri-efendi-ama-nikriz.4560/"
    },
    {
        "id": 7,
        "eser": "Düştüm Aşkın Seline Vardım Bağdat İline - Muzaffer Ozak (Aşki) - Karcığar",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/dustum-askin-seline-vardim-bagdat-iline-muzaffer-ozak-aski-karcigar.12847/"
    },
    {
        "id": 8,
        "eser": "Zikrimiz Esrar-ı Hakdır Canımız Hayran-ı Hu - Belirsiz - Hisar",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/zikrimiz-esrar-i-hakdir-canimiz-hayran-i-hu-belirsiz-hisar.39548/"
    },
    {
        "id": 9,
        "eser": "Mehtap Dalgın Bakıyor - Belirsiz - Hüseyni",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/mehtap-dalgin-bakiyor-belirsiz-huseyni.67724/"
    },
    {
        "id": 10,
        "eser": "Mah Yüzüne Aşıkanım - Dede Efendi - Hicaz",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/mah-yuzune-asikanim-dede-efendi-hicaz.24959/"
    },
    {
        "id": 11,
        "eser": "Merhamet Kıl İftirakın İşledi Ta Canıma - İsak Varon - Hüzzam",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/merhamet-kil-iftirakin-isledi-ta-canima-isak-varon-huzzam.67731/"
    },
    {
        "id": 12,
        "eser": "Meyl Eder Bu Hüsn ile Kim Görse Ey Gül-Fem Seni - Şakir Ağa - Tanburi, Kemani, Hacı İzzet - Ferahnak",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/meyl-eder-bu-husn-ile-kim-gorse-ey-gul-fem-seni-sakir-aga-tanburi-kemani-haci-izzet-ferahnak.25828/"
    },
    {
        "id": 13,
        "eser": "Bezm-i Alemde Meserret Bana Canan iledir - Sultan III.Selim (İlhami) - Zavil",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/bezm-i-alemde-meserret-bana-canan-iledir-sultan-iii-selim-ilhami-zavil.5554/"
    },
    {
        "id": 14,
        "eser": "Peşrev - Belirsiz - Irak",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/pesrev-belirsiz-irak.40716/"
    },
    {
        "id": 15,
        "eser": "Kamet-i Yare Nazar Kıl Nahl-i Mevzun Böyledir - Dellalzade - Muhayyer Buselik",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/kamet-i-yare-nazar-kil-nahl-i-mevzun-boyledir-dellalzade-muhayyer-buselik.23284/"
    },
    {
        "id": 16,
        "eser": "Batan Gün Kana Benziyor - Sadettin Kaynak - Muhayyer",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/batan-gun-kana-benziyor-sadettin-kaynak-muhayyer.4327/"
    },
    {
        "id": 17,
        "eser": "Ruhumda Ah Bir Yetim Gülüşü Var - Belirsiz - Segah",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/ruhumda-ah-bir-yetim-gulusu-var-belirsiz-segah.29419/"
    },
    {
        "id": 18,
        "eser": "Ne Devlettir Ki Dildarım Sen Oldun - Neşet Ersoy - Bestenigar",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/ne-devlettir-ki-dildarim-sen-oldun-neset-ersoy-bestenigar.26616/"
    },
    {
        "id": 19,
        "eser": "Reh-i Aşkında Edip Kaddimi Kütah Gönül - Dede Efendi - Hüzzam",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/reh-i-askinda-edip-kaddimi-kutah-gonul-dede-efendi-huzzam.29278/"
    },
    {
        "id": 20,
        "eser": "Nice Bir Eşk-i Firakınla Pür Olsun Gözümüz - Ebu-bekir Ağa - Şehnaz",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/nice-bir-esk-i-firakinla-pur-olsun-gozumuz-ebu-bekir-aga-sehnaz.27604/"
    },
    {
        "id": 21,
        "eser": "Firakınla Ederken Ah ü Nale - İsmail Hakkı Bey (Muallim) - Rekib",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/firakinla-ederken-ah-u-nale-ismail-hakki-bey-muallim-rekib.15039/"
    },
    {
        "id": 22,
        "eser": "O Şuha Arz-ı Niyaz Etmeye Şitab Ettim - Ebu-Bekir Ağa - Eviç",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/o-suha-arz-i-niyaz-etmeye-sitab-ettim-ebu-bekir-aga-evic.28117/"
    },
    {
        "id": 23,
        "eser": "Ey Şehinşah-ı Risalet Vey Habib-i Kibriya - İsmail Hakkı Bey (Muallim) - Acem Aşiran",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/ey-sehinsah-i-risalet-vey-habib-i-kibriya-ismail-hakki-bey-muallim-acem-asiran.14582/"
    },
    {
        "id": 24,
        "eser": "Ey Resul-i Kibriya Ser-Tac-ı Alem Şah-ı Din - İsmail Hakkı Bey (Muallim) - Hüseyni",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/ey-resul-i-kibriya-ser-tac-i-alem-sah-i-din-ismail-hakki-bey-muallim-huseyni.14449/"
    },
    {
        "id": 25,
        "eser": "Ey Vekil-i Fahr-i Alem Padişah-ı Kam-ran - İsmail Hakkı Bey (Muallim) - Ferahfeza",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/ey-vekil-i-fahr-i-alem-padisah-i-kam-ran-ismail-hakki-bey-muallim-ferahfeza.14659/"
    },
    {
        "id": 26,
        "eser": "Daim Etsin Hazret-i Sultan Hamid Hanı Hüda - İsmail Hakkı Bey (Muallim) - Hicaz",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/daim-etsin-hazret-i-sultan-hamid-hani-huda-ismail-hakki-bey-muallim-hicaz.10925/"
    },
    {
        "id": 27,
        "eser": "Ey Nebiler Serveri Ahir-Zaman Peygamberi - İsmail Hakkı Bey (Muallim) - Hicaz",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/ey-nebiler-serveri-ahir-zaman-peygamberi-ismail-hakki-bey-muallim-hicaz.14383/"
    },
    {
        "id": 28,
        "eser": "Evlerinin Önü Yoldur Yolaktır - İsmail Hakkı Bey (Muallim) - Zavil",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/evlerinin-onu-yoldur-yolaktir-ismail-hakki-bey-muallim-zavil.13749/"
    },
    {
        "id": 29,
        "eser": "Bahar Erse Yine Sahra Serapa Lalezar Olsa - Ebu-Bekir Ağa - Muhayyer",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/bahar-erse-yine-sahra-serapa-lalezar-olsa-ebu-bekir-aga-muhayyer.3481/"
    },
    {
        "id": 30,
        "eser": "Kavli De Kaddi Gibi Rast Olsa Ol Mehveşin - Ahmet Avni Konuk - Rast",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/kavli-de-kaddi-gibi-rast-olsa-ol-mehvesin-ahmet-avni-konuk-rast.23684/"
    },
    {
        "id": 31,
        "eser": "Çün Doğup Tutdu Cihan Yüzünü Hüsnün Güneşi (III) - İsmail Hakkı Bey (Muallim) - Çargah",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/cun-dogup-tutdu-cihan-yuzunu-husnun-gunesi-iii-ismail-hakki-bey-muallim-cargah.10764/"
    },
    {
        "id": 32,
        "eser": "Tehi Sanman Siz Beni Dost Yüzün Görüp Geldim - Ali Şirügani Dede - Eviç",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/tehi-sanman-siz-beni-dost-yuzun-gorup-geldim-ali-sirugani-dede-evic.35470/"
    },
    {
        "id": 33,
        "eser": "Cepheden Toplar Ejder Gibi Bar-Efgen - İsmail Hakkı Bey (Muallim) - Mahur",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/cepheden-toplar-ejder-gibi-bar-efgen-ismail-hakki-bey-muallim-mahur.9871/"
    },
    {
        "id": 34,
        "eser": "Bu Hüsn ile Sen Dilbera Bir Bi-vefa Cananesin - Dede Efendi - Rast",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/bu-husn-ile-sen-dilbera-bir-bi-vefa-cananesin-dede-efendi-rast.8860/"
    },
    {
        "id": 35,
        "eser": "Bişnev Ez Ney Çün Hikayet Miküned (Ferahfeza Âyîn-i Şerîfi) - Dede Efendi - Ferahfeza",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/bisnev-ez-ney-cun-hikayet-mikuned-ferahfeza-ayin-i-serifi-dede-efendi-ferahfeza.8239/"
    },
    {
        "id": 36,
        "eser": "O Gözler Bana Hala Eskisinden Yabancı - Şefik - Hüseyni",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/o-gozler-bana-hala-eskisinden-yabanci-sefik-huseyni.27947/"
    },
    {
        "id": 37,
        "eser": "Bir Bi-Bedel Şuh-i Cihan - Dede Efendi - Bayati",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/bir-bi-bedel-suh-i-cihan-dede-efendi-bayati.6339/"
    },
    {
        "id": 38,
        "eser": "Alem Ağlarken Bütün Benim Dil-i Na-Şadıma - İsmail Hakkı Bey (Muallim) - Suzinak",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/alem-aglarken-butun-benim-dil-i-na-sadima-ismail-hakki-bey-muallim-suzinak.1106/"
    },
    {
        "id": 39,
        "eser": "Bülaceb Derya-Dil ü (Suzinak Âyîn-i Şerîfi) - Haşim Bey - Müezzinbaşı, Hacı - Suzinak",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/bulaceb-derya-dil-u-suzinak-ayin-i-serifi-hasim-bey-muezzinbasi-haci-suzinak.9319/"
    },
    {
        "id": 40,
        "eser": "Dil Verip Oldum Mübtela - Ali Rıza Şengel (Eyyubi) - Arazbar",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/dil-verip-oldum-mubtela-ali-riza-sengel-eyyubi-arazbar.11758/"
    },
    {
        "id": 41,
        "eser": "Bend Oldu Dil Bir Şuh-i Cihane - Dede Efendi - Nühüft",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/bend-oldu-dil-bir-suh-i-cihane-dede-efendi-nuhuft.5017/"
    },
    {
        "id": 42,
        "eser": "Neyleyeyim Dünyayı Bana Allahım Gerek - Belirsiz - Kürdi",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/neyleyeyim-dunyayi-bana-allahim-gerek-belirsiz-kurdi.27567/"
    },
    {
        "id": 43,
        "eser": "Cana Seni Ben Mihr-i Vefa Sahibi Sandım - Sinan Mikail - Bayati",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/cana-seni-ben-mihr-i-vefa-sahibi-sandim-sinan-mikail-bayati.9616/"
    },
    {
        "id": 44,
        "eser": "Saz Semaisi - Osman Efendi (Neyzen) - Neveser",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/saz-semaisi-osman-efendi-neyzen-neveser.42370/"
    },
    {
        "id": 45,
        "eser": "Kurretül Ayn-i Habib-i Kibriyasın Ya Hüseyn - Nuri Bey (Bolahenk) - Hüseyni",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/kurretul-ayn-i-habib-i-kibriyasin-ya-huseyn-nuri-bey-bolahenk-huseyni.24545/"
    },
    {
        "id": 46,
        "eser": "Ey Şehr-i Nüzul-i Sure Bais Oldun Çok Sürure - Nuri Bey (Bolahenk) - Acem Aşiran",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/ey-sehr-i-nuzul-i-sure-bais-oldun-cok-surure-nuri-bey-bolahenk-acem-asiran.14587/"
    },
    {
        "id": 47,
        "eser": "Cemalin Aleme Mihr-i Münevver ya Resulallah - Nuri Bey (Bolahenk) - Eviç",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/cemalin-aleme-mihr-i-munevver-ya-resulallah-nuri-bey-bolahenk-evic.9814/"
    },
    {
        "id": 48,
        "eser": "Saz Semaisi - Muhittin Erev - Bayati",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/saz-semaisi-muhittin-erev-bayati.43054/"
    },
    {
        "id": 49,
        "eser": "Kâkülünü Çözersin (Beyoğlunda Gezersin) Gözlerini Süzersin - Rıza Bey - Giriftzen - Mahur",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/kakulunu-cozersin-beyoglunda-gezersin-gozlerini-suzersin-riza-bey-giriftzen-mahur.5549/"
    },
    {
        "id": 50,
        "eser": "Tuti-i Mucize-Guyem Ne Desem Laf Değil - Koca Osman Efendi - Segah",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/tuti-i-mucize-guyem-ne-desem-laf-degil-koca-osman-efendi-segah.35771/"
    },
    {
        "id": 51,
        "eser": "Gözümde Özleyiş Gönlümde Acı - Selahattin İnal - Buselik",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/gozumde-ozleyis-gonlumde-aci-selahattin-inal-buselik.18249/"
    },
    {
        "id": 52,
        "eser": "Hamd Ane ki Kıldı Halka Rahmet (Bestenigar Âyîn-i Şerîfi) - Hüseyin Sadettin Arel - Bestenigar",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/hamd-ane-ki-kildi-halka-rahmet-bestenigar-ayin-i-serifi-huseyin-sadettin-arel-bestenigar.19813/"
    },
    {
        "id": 53,
        "eser": "Yine Ahlar Etti Peyda - Dede Efendi - Rast",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/yine-ahlar-etti-peyda-dede-efendi-rast.38580/"
    },
    {
        "id": 54,
        "eser": "Bir Gören Yok Bilmiyorlar Nerdesin - Mesud Cemil - Sultani Yegah",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/bir-goren-yok-bilmiyorlar-nerdesin-mesud-cemil-sultani-yegah.6779/"
    },
    {
        "id": 55,
        "eser": "Aşıkların Eğlencesi İsm-i Zatın ya Rabbena - Belirsiz - Gerdaniye",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/asiklarin-eglencesi-ism-i-zatin-ya-rabbena-belirsiz-gerdaniye.2092/"
    },
    {
        "id": 56,
        "eser": "Solgun Durma İsteklen - Münir Nurettin Selçuk - Hüzzam",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/solgun-durma-isteklen-munir-nurettin-selcuk-huzzam.33694/"
    },
    {
        "id": 57,
        "eser": "Gel Azmedelim Bu Gece Göksuya Beraber - Sultan III.Selim (İlhami) - Nihavend",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/gel-azmedelim-bu-gece-goksuya-beraber-sultan-iii-selim-ilhami-nihavend.15544/"
    },
    {
        "id": 58,
        "eser": "Senden Bilirim Yok Bana Bir Faide Ey Gül - Ali Efendi (Tanburi) - Hüseyni",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/senden-bilirim-yok-bana-bir-faide-ey-gul-ali-efendi-tanburi-huseyni.31401/"
    },
    {
        "id": 59,
        "eser": "Seyr-i Mehtab Edelim Gel Bu Şeb Ey Mehlika - Mehmet Yürü (Nasibin) - Acem Kürdi",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/seyr-i-mehtab-edelim-gel-bu-seb-ey-mehlika-mehmet-yuru-nasibin-acem-kurdi.33407/"
    },
    {
        "id": 60,
        "eser": "Allah Allah Hu İleyke Netevve Hu - Ali Ufki - Hüseyni",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/allah-allah-hu-ileyke-netevve-hu-ali-ufki-huseyni.1223/"
    },
    {
        "id": 61,
        "eser": "Zat-ı Pak-i Mustafa'ya Aşıkım - Mustafa Hakan Alvan - Hicaz",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/zat-i-pak-i-mustafaya-asikim-mustafa-hakan-alvan-hicaz.71725/"
    },
    {
        "id": 62,
        "eser": "Lal Olursun Söylesem Bir Fıkra Tab-ı Sineden - Münir Nurettin Selçuk - Nihavend",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/lal-olursun-soylesem-bir-fikra-tab-i-sineden-munir-nurettin-selcuk-nihavend.24745/"
    },
    {
        "id": 63,
        "eser": "Yandı Canım Hicrile Vasl-ı Ruy-i Yar İsterem - Refik Fersan - Tanburi - Selmek",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/yandi-canim-hicrile-vasl-i-ruy-i-yar-isterem-refik-fersan-tanburi-selmek.37406/"
    },
    {
        "id": 64,
        "eser": "Ey Hüdadan Lutf u İhsan İsteyen - Kani Karaca - Hafız - Rast",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/ey-hudadan-lutf-u-ihsan-isteyen-kani-karaca-hafiz-rast.14237/"
    },
    {
        "id": 65,
        "eser": "Saz Semaisi - Belirsiz - Irak",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/saz-semaisi-belirsiz-irak.42865/"
    },
    {
        "id": 66,
        "eser": "Gönül Avare Kaldı Yar Elinden - Zeki Arif Ataergin - Sipihr",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/gonul-avare-kaldi-yar-elinden-zeki-arif-ataergin-sipihr.17173/"
    },
    {
        "id": 67,
        "eser": "Çün Sana Gönlüm Müptela Düştü - Hafız Post (Mehmed Çelebi, İmamzade) - Hüseyni",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/cun-sana-gonlum-muptela-dustu-hafiz-post-mehmed-celebi-imamzade-huseyni.10792/"
    },
    {
        "id": 68,
        "eser": "Ben Bilmez İdim Gizli Ayan Hep Sen İmişsin - Dede Efendi - Suzinak",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/ben-bilmez-idim-gizli-ayan-hep-sen-imissin-dede-efendi-suzinak.4602/"
    },
    {
        "id": 69,
        "eser": "Sen Ey Serv-i Revan Ruhsarı Gülgun - Ali Bey (Enderuni-hanende) - Uşşak",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/sen-ey-serv-i-revan-ruhsari-gulgun-ali-bey-enderuni-hanende-ussak.30966/"
    },
    {
        "id": 70,
        "eser": "Aram Edemem Yare Nigah Eylemedikçe - Abdülaziz Efendi (Hekimbaşı) - Bayati",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/aram-edemem-yare-nigah-eylemedikce-abdulaziz-efendi-hekimbasi-bayati.1659/"
    },
    {
        "id": 71,
        "eser": "Ya Men Yuhibbu Eninul Abdi Finnedemi - Ali Efendi (Tanburi) - Rast",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/ya-men-yuhibbu-eninul-abdi-finnedemi-ali-efendi-tanburi-rast.36943/"
    },
    {
        "id": 72,
        "eser": "On Kere Demedim Mi Sana Sevme Dokuz Yar - Belirsiz - Eviç",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/on-kere-demedim-mi-sana-sevme-dokuz-yar-belirsiz-evic.28351/"
    },
    {
        "id": 73,
        "eser": "Her Telden (Dilden) Ol Meh Çalmıyor - Arif Bey (Hacı) - Rast",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/her-telden-dilden-ol-meh-calmiyor-arif-bey-haci-rast.21146/"
    },
    {
        "id": 74,
        "eser": "Renc-i Hatır Vermesin Feryad Ü Efganlar Sana - Ali Efendi (Tanburi) - Nişabur",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/renc-i-hatir-vermesin-feryad-u-efganlar-sana-ali-efendi-tanburi-nisabur.29292/"
    },
    {
        "id": 75,
        "eser": "Menendin Yok Beyim Bir Meh-likasın - Ali Efendi (Tanburi) - Hicazkar",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/menendin-yok-beyim-bir-meh-likasin-ali-efendi-tanburi-hicazkar.25525/"
    },
    {
        "id": 76,
        "eser": "İzhar Edemem Elbette Sana Aşkımı Halim - Ali Efendi (Tanburi) - Yegah",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/izhar-edemem-elbette-sana-askimi-halim-ali-efendi-tanburi-yegah.22641/"
    },
    {
        "id": 77,
        "eser": "Peşrev - Mehmet Reşat Aysu - Muhayyer Kürdi",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/pesrev-mehmet-resat-aysu-muhayyer-kurdi.40558/"
    },
    {
        "id": 78,
        "eser": "Ben Esir-i Derd-i Hicranım Vefasız Yare Ne - Suphi Ziya Özbekkan - Isfahan",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/ben-esir-i-derd-i-hicranim-vefasiz-yare-ne-suphi-ziya-ozbekkan-isfahan.4727/"
    },
    {
        "id": 79,
        "eser": "Gördüm Bugün O Güzeli - Kemani Agop Efendi - Hicazkar",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/gordum-bugun-o-guzeli-kemani-agop-efendi-hicazkar.17574/"
    },
    {
        "id": 80,
        "eser": "Peşrev - Rüştü Eriç - Udi - Yegah",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/pesrev-rustu-eric-udi-yegah.41687/"
    },
    {
        "id": 81,
        "eser": "Derd-i Gamla Geçti Ömrüm Daima Bi-neşeyim - Agopos Alyanak (Kemani) - Şedaraban",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/derd-i-gamla-gecti-omrum-daima-bi-neseyim-agopos-alyanak-kemani-sedaraban.11300/"
    },
    {
        "id": 82,
        "eser": "Ya İlahi Senden Uddet - Ali Ufki - Acem",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/ya-ilahi-senden-uddet-ali-ufki-acem.36917/"
    },
    {
        "id": 83,
        "eser": "Hemişe Dilde Sühan Elde Saz Karımdır - Mustafa Efendi (Tabi) - Sazkar",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/hemise-dilde-suhan-elde-saz-karimdir-mustafa-efendi-tabi-sazkar.20682/"
    },
    {
        "id": 84,
        "eser": "Ah Eylediğim Serv-i Hıramanın İçindir - Bekir Sıdkı Sezgin - Hisar Buselik",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/ah-eyledigim-serv-i-hiramanin-icindir-bekir-sidki-sezgin-hisar-buselik.634/"
    },
    {
        "id": 85,
        "eser": "Ya Hazret-i Mevlana ya Habiballah Resul-i Halık-i Yekta Tüyi - Belirsiz (Atfen Itrî) - Rast",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/ya-hazret-i-mevlana-ya-habiballah-resul-i-halik-i-yekta-tuyi-belirsiz-atfen-itri-rast.36886/"
    },
    {
        "id": 86,
        "eser": "Saz Semaisi - Hüseyin Erbay - Nihavend",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/saz-semaisi-huseyin-erbay-nihavend.44582/"
    },
    {
        "id": 87,
        "eser": "Çün Doğup Tuttu Cihan Yüzünü Hüsnün Güneşi(*A) - Itri (Buhurizade Mustafa Efendi) - Rast",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/cun-dogup-tuttu-cihan-yuzunu-husnun-gunesi-a-itri-buhurizade-mustafa-efendi-rast.10786/"
    },
    {
        "id": 88,
        "eser": "Saz Semaisi - Şevki Dede (Kudümzenbaşı) - Rast",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/saz-semaisi-sevki-dede-kudumzenbasi-rast.43188/"
    },
    {
        "id": 89,
        "eser": "Can-ı Kullab-ı Ser-i Zülfün Çeker Senden Yana - Itri (Buhurizade Mustafa Efendi) - Nikriz",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/can-i-kullab-i-ser-i-zulfun-ceker-senden-yana-itri-buhurizade-mustafa-efendi-nikriz.9687/"
    },
    {
        "id": 90,
        "eser": "Yandım Yakıldım Ben Nar-ı Aşka - Dede Efendi - Isfahan",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/yandim-yakildim-ben-nar-i-aska-dede-efendi-isfahan.37442/"
    },
    {
        "id": 91,
        "eser": "Menba-ı İlm-i Hüdasın ya Muhammed Mustafa - Rifat - Acem Kürdi",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/menba-i-ilm-i-hudasin-ya-muhammed-mustafa-rifat-acem-kurdi.25494/"
    },
    {
        "id": 92,
        "eser": "Sinemde Bir Tutuşmuş Yanmış Ocağ Olaydı - Belirsiz - Hüseyni",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/sinemde-bir-tutusmus-yanmis-ocag-olaydi-belirsiz-huseyni.33565/"
    },
    {
        "id": 93,
        "eser": "Seni Gördükçe Titriyor Yüreğim - Salih Efendi (Kemani-bülbüli) - Hicaz",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/seni-gordukce-titriyor-yuregim-salih-efendi-kemani-bulbuli-hicaz.31647/"
    },
    {
        "id": 94,
        "eser": "Söyletme Beni Derdim Büyüktür - Belirsiz - Uşşak",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/soyletme-beni-derdim-buyuktur-belirsiz-ussak.34081/"
    },
    {
        "id": 95,
        "eser": "Neş'edir Bâğ-ı Hayâtı Hep Kemâle Erdiren - Bimen Şen (?) - Vech-i Arazbar",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/nesedir-bag-i-hayati-hep-kemale-erdiren-bimen-sen-vech-i-arazbar.71712/"
    },
    {
        "id": 96,
        "eser": "Sular Gibi Çağlarım Ben - Dede Efendi - Gülizar",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/sular-gibi-caglarim-ben-dede-efendi-gulizar.34188/"
    },
    {
        "id": 97,
        "eser": "Su Gibi Çağladığım Derunum Dağladığım (Ciğerim Bağladığım) - Dede Efendi - Hüseyni Aşiran",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/su-gibi-cagladigim-derunum-dagladigim-cigerim-bagladigim-dede-efendi-huseyni-asiran.34154/"
    },
    {
        "id": 98,
        "eser": "Ey Hasret-i Huban-ı Cihan Ruy-i Hôşest (Şevkutarab Âyîn-i Şerîfi) - Dede Efendi - Şevkutarab",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/ey-hasret-i-huban-i-cihan-ruy-i-hosest-sevkutarab-ayin-i-serifi-dede-efendi-sevkutarab.14219/"
    },
    {
        "id": 99,
        "eser": "O Mahitabı Acep Gösterir mi Bana Felek - Dede Efendi - Hicaz",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/o-mahitabi-acep-gosterir-mi-bana-felek-dede-efendi-hicaz.28054/"
    },
    {
        "id": 100,
        "eser": "Amade Olur Zevk-i Ceme Zümre-i Rindan - Zekai Dede - Karcığar",
        "makam": "İçerikten bakılacak",
        "usûl": "İçerikten bakılacak",
        "güfte": "Bilinmiyor",
        "bestekâr": "İçerikten bakılacak",
        "form": "İçerikten bakılacak",
        "resim": "",
        "kaynakLink": "https://divanmakam.com/forum/amade-olur-zevk-i-ceme-zumre-i-rindan-zekai-dede-karcigar.1367/"
    }
];
