const eserler = [
    {"id": 1, "eser": "Beni bîgâne-i hâb etti keder", "makam": "Sûznâk", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "resim": "",
    {"id": 2, "eser": "Bir Nigahın Gönlümü Etti Esir-i Aşkın Ah", "makam": "Eviç", "bestekâr": "Tanburî Cemil Bey", "usul": "Aksak", "form": "Şarkı", "resim": "",
    {"id": 3, "eser": "Bir Peri-Sima Güzelsin Hüsnüne Yokdur Baha", "makam": "Sultan-i Yegah", "bestekâr": "Tanburî Cemil Bey", "usul": "Devr-i Hindi", "form": "Şarkı", "resim": "",
    {"id": 4, "eser": "Dağda Tavşanlar Uyur Ninni", "makam": "Hicaz", "bestekâr": "Tanburî Cemil Bey", "usul": "Sofyan", "form": "Ninni", "resim": "",
    {"id": 5, "eser": "Defi Naliş Eylerim Hep Seyr-i Ruhsarınla Ben", "makam": "Kürdili Hicazkar", "bestekâr": "Tanburî Cemil Bey", "usul": "Aksak", "form": "Şarkı", "resim": "",
    {"id": 6, "eser": "Feryad Ki Feryadıma İmdad Edecek Yok", "makam": "Şehnaz", "bestekâr": "Tanburî Cemil Bey", "usul": "Sengin Semai", "form": "Şarkı", "resim": "",
    {"id": 7, "eser": "Gel Ey Saki Bana Sun Bir Piyale", "makam": "Segah", "bestekâr": "Tanburî Cemil Bey", "usul": "Aksak", "form": "Şarkı", "resim": "",
    {"id": 8, "eser": "Görmek İster Gözlerim Her Dem Seni", "makam": "Hüseyni", "bestekâr": "Tanburî Cemil Bey", "usul": "Devr-i Hindi", "form": "Şarkı", "resim": "",
    {"id": 9, "eser": "Gül-Gonca-i Ümmid Gibi Gel Açıl Gül", "makam": "Gülizar", "bestekâr": "Tanburî Cemil Bey", "usul": "Sengin Semai", "form": "Şarkı", "resim": "",
    {"id": 10, "eser": "Gülsitane Eyleyip Tercih Bir Viraneyi", "makam": "Şevkefza", "bestekâr": "Tanburî Cemil Bey", "usul": "Yürük Semai", "form": "Şarkı", "resim": "",
    {"id": 11, "eser": "Hatır-ı Na-şadı Gel Gör Bir Nefes Şadet Beni", "makam": "Segah", "bestekâr": "Tanburî Cemil Bey", "usul": "Ağır Aksak", "form": "Şarkı", "resim": "",
    {"id": 12, "eser": "Hep Saye-i Vaslında Gönül Şad Olacakken", "makam": "Hicaz", "bestekâr": "Tanburî Cemil Bey", "usul": "Sengin Semai", "form": "Şarkı", "resim": "",
    {"id": 13, "eser": "Hicaz Taksim", "makam": "Hicaz", "bestekâr": "Tanburî Cemil Bey", "usul": "Serbest", "form": "Taksim", "resim": "",
    {"id": 14, "eser": "Hicrinle Füzun Olmadan Ahzan-ı Mezalım", "makam": "Kürdili Hicazkar", "bestekâr": "Tanburî Cemil Bey", "usul": "Aksak", "form": "Şarkı", "resim": "",
    {"id": 15, "eser": "Longa (Sirto) - Nikriz", "makam": "Nikriz", "bestekâr": "Tanburî Cemil Bey", "usul": "Nim Sofyan", "form": "Longa", "resim": "",
    {"id": 16, "eser": "Longa - Nihavend", "makam": "Nihavend", "bestekâr": "Tanburî Cemil Bey", "usul": "Nim Sofyan", "form": "Longa", "resim": "",
    {"id": 17, "eser": "Matemzedeyim Külbe-i Ahzanımı Gel Gör", "makam": "Hicaz", "bestekâr": "Tanburî Cemil Bey", "usul": "Aksak", "form": "Şarkı", "resim": "",
    {"id": 18, "eser": "Nazirin Yok Senin Ey Mah Yerde", "makam": "Eviç", "bestekâr": "Tanburî Cemil Bey", "usul": "Aksak Semai", "form": "Şarkı", "resim": "",
    {"id": 19, "eser": "Nihandır Dideden Gerçi Cemalin", "makam": "Müstear", "bestekâr": "Tanburî Cemil Bey", "usul": "Yürük Semai", "form": "Şarkı", "resim": "",
    {"id": 20, "eser": "Oyun Havası - Hüseyni", "makam": "Hüseyni", "bestekâr": "Tanburî Cemil Bey", "usul": "Nim Sofyan", "form": "Oyun Havası", "resim": "",
    {"id": 21, "eser": "Pesendide Kemençe Taksimi", "makam": "Pesendîde", "bestekâr": "Tanburî Cemil Bey", "usul": "Serbest", "form": "Taksim", "resim": "",
    {"id": 22, "eser": "Peşrev - Ferahfeza", "makam": "Ferahfeza", "bestekâr": "Tanburî Cemil Bey", "usul": "Muhammes", "form": "Peşrev", "resim": "",
    {"id": 23, "eser": "Peşrev - Hicazkar", "makam": "Hicazkar", "bestekâr": "Tanburî Cemil Bey", "usul": "Muhammes", "form": "Peşrev", "resim": "",
    {"id": 24, "eser": "Peşrev - Isfahan", "makam": "Isfahan", "bestekâr": "Tanburî Cemil Bey", "usul": "Devr-i Kebir", "form": "Peşrev", "resim": "",
    {"id": 25, "eser": "Peşrev - Kürdili Hicazkar", "makam": "Kürdili Hicazkar", "bestekâr": "Tanburî Cemil Bey", "usul": "Muhammes", "form": "Peşrev", "resim": "",
    {"id": 26, "eser": "Peşrev - Mahur", "makam": "Mahur", "bestekâr": "Tanburî Cemil Bey", "usul": "Muhammes", "form": "Peşrev", "resim": "",
    {"id": 27, "eser": "Peşrev - Muhayyer", "makam": "Muhayyer", "bestekâr": "Tanburî Cemil Bey", "usul": "Devr-i Kebir", "form": "Peşrev", "resim": "",
    {"id": 28, "eser": "Peşrev - Neva", "makam": "Neva", "bestekâr": "Tanburî Cemil Bey", "usul": "Devr-i Kebir", "form": "Peşrev", "resim": "",
    {"id": 29, "eser": "Peşrev - Şedaraban", "makam": "Şedaraban", "bestekâr": "Tanburî Cemil Bey", "usul": "Fahte", "form": "Peşrev", "resim": "",
    {"id": 30, "eser": "Pür-lerze Olur Ruyini Gördükçe Cenanım", "makam": "Muhayyer", "bestekâr": "Tanburî Cemil Bey", "usul": "Sengin Semai", "form": "Şarkı", "resim": "",
    {"id": 31, "eser": "Saz Semaisi - Bestenigar", "makam": "Bestenigar", "bestekâr": "Tanburî Cemil Bey", "usul": "Aksak Semai", "form": "Saz Semaisi", "resim": "",
    {"id": 32, "eser": "Saz Semaisi - Ferahfeza", "makam": "Ferahfeza", "bestekâr": "Tanburî Cemil Bey", "usul": "Aksak Semai", "form": "Saz Semaisi", "resim": "",
    {"id": 33, "eser": "Saz Semaisi - Hicaz", "makam": "Hicaz", "bestekâr": "Tanburî Cemil Bey", "usul": "Yürük Semai", "form": "Saz Semaisi", "resim": "",
    {"id": 34, "eser": "Saz Semaisi - Hicazkar", "makam": "Hicazkar", "bestekâr": "Tanburî Cemil Bey", "usul": "Aksak Semai", "form": "Saz Semaisi", "resim": "",
    {"id": 35, "eser": "Saz Semaisi - Isfahan", "makam": "Isfahan", "bestekâr": "Tanburî Cemil Bey", "usul": "Aksak Semai", "form": "Saz Semaisi", "resim": "",
    {"id": 36, "eser": "Saz Semaisi - Nihavend", "makam": "Nihavend", "bestekâr": "Tanburî Cemil Bey", "usul": "Aksak Semai", "form": "Saz Semaisi", "resim": "",
    {"id": 37, "eser": "Saz Semaisi - Şedaraban", "makam": "Şedaraban", "bestekâr": "Tanburî Cemil Bey", "usul": "Aksak Semai", "form": "Saz Semaisi", "resim": "",
    {"id": 38, "eser": "Saz Semaisi - Suzidilara", "makam": "Suzidilara", "bestekâr": "Tanburî Cemil Bey", "usul": "Aksak Semai", "form": "Saz Semaisi", "resim": "",
    {"id": 39, "eser": "Saz Semaisi - Muhayyer", "makam": "Muhayyer", "bestekâr": "Cemil Bey & Nevres Bey", "usul": "Aksak Semai", "form": "Saz Semaisi", "resim": "",
    {"id": 40, "eser": "Şedaraban Taksim", "makam": "Şedaraban", "bestekâr": "Tanburî Cemil Bey", "usul": "Serbest", "form": "Taksim", "resim": "",
    {"id": 41, "eser": "Sen Gül Eğlen Şad-man Ol", "makam": "Mahur", "bestekâr": "Tanburî Cemil Bey", "usul": "Ağır Aksak", "form": "Şarkı", "resim": "",
    {"id": 42, "eser": "Sevdim Seni Ey İşve-baz", "makam": "Nihavend", "bestekâr": "Tanburî Cemil Bey", "usul": "Semai", "form": "Şarkı", "resim": "",
    {"id": 43, "eser": "Sirto - Nikriz", "makam": "Nikriz", "bestekâr": "Tanburî Cemil Bey", "usul": "Nim Sofyan", "form": "Sirto", "resim": "",
    {"id": 44, "eser": "Suzidilârâ Tanbur Taksimi", "makam": "Sûzdilârâ", "bestekâr": "Tanburî Cemil Bey", "usul": "Serbest", "form": "Taksim", "resim": "",
    {"id": 45, "eser": "Taksim - Hicaz", "makam": "Hicaz", "bestekâr": "Tanburî Cemil Bey", "usul": "Serbest", "form": "Taksim", "resim": "",
    {"id": 46, "eser": "Taksim - Isfahan", "makam": "Isfahan", "bestekâr": "Tanburî Cemil Bey", "usul": "Serbest", "form": "Taksim", "resim": "",
    {"id": 47, "eser": "Taksim - Nihavend", "makam": "Nihavend", "bestekâr": "Tanburî Cemil Bey", "usul": "Nim Sofyan", "form": "Taksim", "resim": "",
    {"id": 48, "eser": "Taksim - Nikriz", "makam": "Nikriz", "bestekâr": "Tanburî Cemil Bey", "usul": "Serbest", "form": "Taksim", "resim": "",
    {"id": 49, "eser": "Taksim - Rast", "makam": "Rast", "bestekâr": "Tanburî Cemil Bey", "usul": "Serbest", "form": "Taksim", "resim": "",
    {"id": 50, "eser": "Taksim - Saba", "makam": "Saba", "bestekâr": "Tanburî Cemil Bey", "usul": "Serbest", "form": "Taksim", "resim": "",
    {"id": 51, "eser": "Taksim - Uşşak", "makam": "Uşşak", "bestekâr": "Tanburî Cemil Bey", "usul": "Serbest", "form": "Taksim", "resim": "",
    {"id": 52, "eser": "Var İken Zatında Böyle Hüsn Ü An Olma Nihan", "makam": "Mahur", "bestekâr": "Tanburî Cemil Bey", "usul": "Ağır Aksak", "form": "Şarkı", "resim": "",
    {"id": 53, "eser": "Zeybek Havası - Nikriz (1)", "makam": "Nikriz", "bestekâr": "Tanburî Cemil Bey", "usul": "Aksak", "form": "Zeybek", "resim": "",
    {"id": 54, "eser": "Zeybek Havası - Nikriz (2)", "makam": "Nikriz", "bestekâr": "Tanburî Cemil Bey", "usul": "Aksak", "form": "Zeybek", "resim": "",
    {"id": 55, "eser": "Zeybek Havası - Rast", "makam": "Rast", "bestekâr": "Tanburî Cemil Bey", "usul": "Aksak", "form": "Zeybek", "resim": "",
];
