const eserler = [
            { "id": 1, "eser": "Beni bîgâne-i hâb etti keder", "makam": "Sûznâk", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "notalar/Beni bîgâne-i hâb.pdf", "icrâ": "https://youtu.be/h8e5R6--XjU?si=Kb_6-KZ21uKwsHBh", "güfte": "Beni bîgâne-i hâb etti keder\nDüşünür âh ederim tâ-be-seher\nArtırır derdimi muzlim geceler\nDüşünür âh ederim tâ-be-seher\n\nFirkat-i yâr ile kaldım nâçâr\nOldu bin dert ile gönül bîmâr\nEtti gam hâtırımı pek âzâr\nDüşünür âh ederim tâ-be-seher" },
            { "id": 2, "eser": "Bir nigâhın gönlümü etti esîr-i aşkın âh", "makam": "Evc", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "notalar/Bir nigâhın gönlümü.pdf", "icrâ": "https://youtu.be/GE1Am4-OIlE?si=UNYFIx2VaIT3CivC", "güfte": "Bir nigâhın gönlümü etti esîr-i aşkın âh\nHer zamân kan ağlarım derdinle ey çeşm-i siyâh\nYârelendi tîr-i müjgânınla kalbim gamm-penâh\nHer zamân kan ağlarım derdinle ey çeşm-i siyâh" },
            { "id": 3, "eser": "Bir perî-sîmâ güzelsin hüsnüne yoktur bahâ​", "makam": "Sultânî-yegâh", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Devr-i Hindî", "form": "Şarkı", "nota": "notalar/Bir perî-sîmâ güzelsin.pdf", "icrâ": "https://youtu.be/HN3nJWCuK-Q?si=mqbChwVNYGotc7kA", "güfte": "Bir perî-sîmâ güzelsin hüsnüne yoktur bahâ\nDûş olan sevdâ-yı zülfünden baş almaz bir daha\nTîr-î gamzenden reh-i aşkında kim bulmuş rehâ\nDûş olan sevdâ-yı zülfünden baş almaz bir daha\n\nAzm-i gülzâr eyledikçe gülsitân handân olur\nMakdemin tebrîke bülbüller negam-efşân olur\nSünbül ü gül serv ü ar'ar da sana hayrân olur\nDûş olan sevdâ-yı zülfünden baş almaz bir daha" },
            { "id": 4, "eser": "Dağda tavşanlar uyur ninni", "makam": "Hicaz", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Sofyan", "form": "Ninni", "nota": "notalar/Dağda tavşanlar uyur.pdf", "icrâ": "https://youtu.be/-gyHiopghSE?si=wjQmRZRa23VDDrag", "güfte": "Dağda tavşanlar uyur ninni\nEvde koşanlar uyur ninni\nBenim yavrum uyumaz ninni\nUyusun da büyüsün ninni" },
            { "id": 5, "eser": "Def-i nâliş  eylerim hep seyr-i ruhsârınla ben", "makam": "Kürdîli-hicâzkâr", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "notalar/Def-i nâliş eylerim.pdf", "icrâ": "https://youtu.be/Qsabi4EZjM8?si=2NPz7i2RGjnAF328", "güfte": "Def-i nâliş eylerim hep seyr-i ruhsârınla ben\nArz-ı çehre eyle gül şen şâtır ol pîşimde sen\nGayri kurtulsun bu kalb-i pür-enînim giryeden\nArz-ı çehre eyle gül şen şâtır ol pîşimde sen" },
            { "id": 6, "eser": "Feryâd ki feryâdıma imdâd edecek yok", "makam": "Şehnaz", "güftekâr": "Nigâr Hanım", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Sengin semâî", "form": "Şarkı", "nota": "notalar/Feryâd ki feryâdıma.pdf", "icrâ": "https://youtu.be/qzT1SPZL5Mo?si=VwQMCNB9YhQJ1c7c", "güfte": "Feryâd ki feryâdıma imdâd edecek yok\nEfsûs ki gammdan beni âzâd edecek yok\nTe'sîr-i muhabbetle yıkılmış müteellim\nVîrâne dili bir daha âbâd edecek yok\nYâ Rab ne için zârî Nigârî şu cihânda\nNâşâd edecek çoksa da dilşâd edecek yok" },
            { "id": 1, "eser": "Gel ey sâkî bana sun bir piyâle", "makam": "Segâh", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "notalar/Gel ey sâkî.pdf", "icrâ": "https://youtu.be/YOW58IyK5LQ?si=fqrIJPqvg3TdQT5j", "güfte": "Gel ey sâkî bana sun bir piyâle\nErişti mevsim-i gül fasl-ı lâle\nHezâr-ı nevbahâr erdi visâle\nGönül hasretle girdi bak ne hâle" },
            { "id": 1, "eser": "Beni bîgâne-i hâb etti keder", "makam": "Sûznâk", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "notalar/beni_bigane.pdf", "icrâ": "https://youtu.be/h8e5R6--XjU?si=Kb_6-KZ21uKwsHBh", "güfte": "Beni bîgâne-i hâb etti keder\nDüşünür âh ederim tâ-be-seher\nArtırır derdimi muzlim geceler\nDüşünür âh ederim tâ-be-seher\n\nFirkat-i yâr ile kaldım nâçâr\nOldu bin dert ile gönül bîmâr\nEtti gam hâtırımı pek âzâr\nDüşünür âh ederim tâ-be-seher" },
            { "id": 1, "eser": "Beni bîgâne-i hâb etti keder", "makam": "Sûznâk", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "notalar/beni_bigane.pdf", "icrâ": "https://youtu.be/h8e5R6--XjU?si=Kb_6-KZ21uKwsHBh", "güfte": "Beni bîgâne-i hâb etti keder\nDüşünür âh ederim tâ-be-seher\nArtırır derdimi muzlim geceler\nDüşünür âh ederim tâ-be-seher\n\nFirkat-i yâr ile kaldım nâçâr\nOldu bin dert ile gönül bîmâr\nEtti gam hâtırımı pek âzâr\nDüşünür âh ederim tâ-be-seher" },
            { "id": 1, "eser": "Beni bîgâne-i hâb etti keder", "makam": "Sûznâk", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "notalar/beni_bigane.pdf", "icrâ": "https://youtu.be/h8e5R6--XjU?si=Kb_6-KZ21uKwsHBh", "güfte": "Beni bîgâne-i hâb etti keder\nDüşünür âh ederim tâ-be-seher\nArtırır derdimi muzlim geceler\nDüşünür âh ederim tâ-be-seher\n\nFirkat-i yâr ile kaldım nâçâr\nOldu bin dert ile gönül bîmâr\nEtti gam hâtırımı pek âzâr\nDüşünür âh ederim tâ-be-seher" },
            
            { "id": 1, "eser": "Beni bîgâne-i hâb etti keder", "makam": "Sûznâk", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "notalar/beni_bigane.pdf", "icrâ": "https://youtu.be/h8e5R6--XjU?si=Kb_6-KZ21uKwsHBh", "güfte": "Beni bîgâne-i hâb etti keder\nDüşünür âh ederim tâ-be-seher\nArtırır derdimi muzlim geceler\nDüşünür âh ederim tâ-be-seher\n\nFirkat-i yâr ile kaldım nâçâr\nOldu bin dert ile gönül bîmâr\nEtti gam hâtırımı pek âzâr\nDüşünür âh ederim tâ-be-seher" },
            { "id": 1, "eser": "Beni bîgâne-i hâb etti keder", "makam": "Sûznâk", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "notalar/beni_bigane.pdf", "icrâ": "https://youtu.be/h8e5R6--XjU?si=Kb_6-KZ21uKwsHBh", "güfte": "Beni bîgâne-i hâb etti keder\nDüşünür âh ederim tâ-be-seher\nArtırır derdimi muzlim geceler\nDüşünür âh ederim tâ-be-seher\n\nFirkat-i yâr ile kaldım nâçâr\nOldu bin dert ile gönül bîmâr\nEtti gam hâtırımı pek âzâr\nDüşünür âh ederim tâ-be-seher" },
            { "id": 1, "eser": "Beni bîgâne-i hâb etti keder", "makam": "Sûznâk", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "notalar/beni_bigane.pdf", "icrâ": "https://youtu.be/h8e5R6--XjU?si=Kb_6-KZ21uKwsHBh", "güfte": "Beni bîgâne-i hâb etti keder\nDüşünür âh ederim tâ-be-seher\nArtırır derdimi muzlim geceler\nDüşünür âh ederim tâ-be-seher\n\nFirkat-i yâr ile kaldım nâçâr\nOldu bin dert ile gönül bîmâr\nEtti gam hâtırımı pek âzâr\nDüşünür âh ederim tâ-be-seher" },

            { "id": 2, "eser": "Hâtır-ı nâşâdı gel gör bir nefes şâd et beni", "makam": "Segâh", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Ağır aksak", "form": "Şarkı", "nota": "", "icrâ": "https://youtu.be/iyaAJ7eYIR8?si=JbEKaFS2ugBSlALT", "güfte": "Hâtır-ı nâşâdı gel gör bir nefes şâd et beni\nKayd-ı hicrândan a zâlim artık âzâd et beni\nHasretinle pek harâbım bârî âbâd et beni\nKayd-ı hicrândan a zâlim artık âzâd et beni\nEy cefâ-cû eyle insâf âşık-ı bîçârene\nMerhem-i lutfunla imdât eyle gel âvârene\nKayd-ı hicrândan a zâlim artık âzâd et beni" },
            { "id": 3, "eser": "Hep sâye-i vaslında gönül şâd olacakken", "makam": "Hicaz", "güftekâr": "Tanbûrî Cemil Bey", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Sengin semâî", "form": "Şarkı", "nota": "", "icrâ": "", "sozler": "Hep sâye-i vaslında..." },
            { "id": 4, "eser": "Hicrinle füzûn olmadan ahzân-ı mezâlim", "makam": "Kürdîli-hicâzkâr", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "", "icrâ": "", "sozler": "Hicrinle füzûn..." },
            { "id": 5, "eser": "Mâtemzedeyim külbe-i ahzânımı gel gör", "makam": "Hicaz", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "", "icrâ": "", "sozler": "Mâtemzedeyim..." },
            { "id": 6, "eser": "Nazîrin yok senin ey mâh yerde", "makam": "Evc", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak semâî", "form": "Şarkı", "nota": "", "icrâ": "", "sozler": "Nazîrin yok senin..." },
            { "id": 7, "eser": "Nihândır dîdeden gerçi cemâlin", "makam": "Müstear", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Yürük semâî", "form": "Şarkı", "nota": "", "icrâ": "", "sozler": "Nihândır dîdeden..." },
            { "id": 8, "eser": "Pür-lerze olur rûyini gördükçe cenânım", "makam": "Muhayyer", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Sengin semâî", "form": "Şarkı", "nota": "", "icrâ": "", "sozler": "Pür-lerze olur..." },
            { "id": 9, "eser": "Sen gül eğlen şâd-mân ol", "makam": "Mâhur", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Ağır aksak", "form": "Şarkı", "nota": "", "icrâ": "", "sozler": "Sen gül eğlen..." },
            { "id": 10, "eser": "Sevdim seni ey işve-bâz", "makam": "Nihâvend", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Semâî", "form": "Şarkı", "nota": "", "icrâ": "", "sozler": "Sevdim seni..." },
            { "id": 11, "eser": "Var iken zâtında böyle hüsn ü ân olma nihân", "makam": "Mâhur", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Ağır aksak", "form": "Şarkı", "nota": "", "icrâ": "", "sozler": "Var iken zâtında..." }
        ]
