const eserler = [
            { "id": 1, "eser": "Beni bîgâne-i hâb etti keder", "makam": "Sûznâk", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "notalar/Beni-bîgâne-i-hâb.pdf", "icrâ": "https://youtu.be/h8e5R6--XjU?si=Kb_6-KZ21uKwsHBh", "güfte": "Beni bîgâne-i hâb etti keder\nDüşünür âh ederim tâ-be-seher\nArtırır derdimi muzlim geceler\nDüşünür âh ederim tâ-be-seher\n\nFirkat-i yâr ile kaldım nâçâr\nOldu bin dert ile gönül bîmâr\nEtti gam hâtırımı pek âzâr\nDüşünür âh ederim tâ-be-seher" },
            { "id": 2, "eser": "Bir nigâhın gönlümü etti esîr-i aşkın âh", "makam": "Evc", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "notalar/Bir-nigâhın-gönlümü.pdf", "icrâ": "https://youtu.be/GE1Am4-OIlE?si=UNYFIx2VaIT3CivC", "güfte": "Bir nigâhın gönlümü etti esîr-i aşkın âh\nHer zamân kan ağlarım derdinle ey çeşm-i siyâh\nYârelendi tîr-i müjgânınla kalbim gamm-penâh\nHer zamân kan ağlarım derdinle ey çeşm-i siyâh" },
            { "id": 3, "eser": "Bir perî-sîmâ güzelsin hüsnüne yoktur bahâ​", "makam": "Sultânî-yegâh", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Devr-i Hindî", "form": "Şarkı", "nota": "notalar/Bir-perî-sîmâ-güzelsin.pdf", "icrâ": "https://youtu.be/HN3nJWCuK-Q?si=mqbChwVNYGotc7kA", "güfte": "Bir perî-sîmâ güzelsin hüsnüne yoktur bahâ\nDûş olan sevdâ-yı zülfünden baş almaz bir daha\nTîr-î gamzenden reh-i aşkında kim bulmuş rehâ\nDûş olan sevdâ-yı zülfünden baş almaz bir daha\n\nAzm-i gülzâr eyledikçe gülsitân handân olur\nMakdemin tebrîke bülbüller negam-efşân olur\nSünbül ü gül serv ü ar'ar da sana hayrân olur\nDûş olan sevdâ-yı zülfünden baş almaz bir daha" },
            { "id": 4, "eser": "Çeçen Kızı", "makam": "Hüseynî", "güftekâr": "Yok", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Nîm-sofyan", "form": "Oyun havâsı", "nota": "notalar/Çeçen-Kızı.pdf", "icrâ": "https://youtu.be/jH95J48swk4?si=bN610sOfrqKBM1Op", "güfte": "Yok", },
            { "id": 5, "eser": "Dağda tavşanlar uyur ninni", "makam": "Hicaz", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Sofyan", "form": "Ninni", "nota": "notalar/Dağda-tavşanlar-uyur.pdf", "icrâ": "https://youtu.be/-gyHiopghSE?si=wjQmRZRa23VDDrag", "güfte": "Dağda tavşanlar uyur ninni\nEvde koşanlar uyur ninni\nBenim yavrum uyumaz ninni\nUyusun da büyüsün ninni" },
            { "id": 6, "eser": "Def-i nâliş  eylerim hep seyr-i ruhsârınla ben", "makam": "Kürdîli-hicâzkâr", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "notalar/Def-i-nâliş-eylerim.pdf", "icrâ": "https://youtu.be/Qsabi4EZjM8?si=2NPz7i2RGjnAF328", "güfte": "Def-i nâliş eylerim hep seyr-i ruhsârınla ben\nArz-ı çehre eyle gül şen şâtır ol pîşimde sen\nGayri kurtulsun bu kalb-i pür-enînim giryeden\nArz-ı çehre eyle gül şen şâtır ol pîşimde sen" },
            { "id": 7, "eser": "Feryâd ki feryâdıma imdâd edecek yok", "makam": "Şehnaz", "güftekâr": "Nigâr Hanım", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Sengin semâî", "form": "Şarkı", "nota": "notalar/Feryâd-ki-feryâdıma.pdf", "icrâ": "https://youtu.be/qzT1SPZL5Mo?si=VwQMCNB9YhQJ1c7c", "güfte": "Feryâd ki feryâdıma imdâd edecek yok\nEfsûs ki gammdan beni âzâd edecek yok\nTe'sîr-i muhabbetle yıkılmış müteellim\nVîrâne dili bir daha âbâd edecek yok\nYâ Rab ne için zârî Nigârî şu cihânda\nNâşâd edecek çoksa da dilşâd edecek yok" },
            { "id": 8, "eser": "Gel ey sâkî bana sun bir piyâle", "makam": "Segâh", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "notalar/Gel-ey-sâkî.pdf", "icrâ": "https://youtu.be/YOW58IyK5LQ?si=fqrIJPqvg3TdQT5j", "güfte": "Gel ey sâkî bana sun bir piyâle\nErişti mevsim-i gül fasl-ı lâle\nHezâr-ı nevbahâr erdi visâle\nGönül hasretle girdi bak ne hâle" },
            { "id": 9, "eser": "Görmek ister gözlerim her dem seni", "makam": "Hüseynî", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Devr-i Hindî", "form": "Şarkı", "nota": "notalar/Görmek-ister-gözlerim.pdf", "icrâ": "https://youtu.be/H6EEr5mh3XY?si=-mVbJXDWWtnsS04y", "güfte": "Görmek ister gözlerim her dem seni\nYâd et Allâh aşkına sen de beni\nÇünki söyler ağlarım ben hep seni\nYâd et Allâh aşkına sen de beni" },
            { "id": 10, "eser": "Gül gonce-i ümîd gibi gel açıl ey gül", "makam": "Gülizar", "güftekâr": "Mahmut Şevket Özdönmez", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Sengin semâî", "form": "Şarkı", "nota": "notalar/Gül-gonce-i-ümîd.pdf", "icrâ": "https://youtu.be/IlFy_rptMaI?si=_GjqAgQS9Ek1Q5sB", "güfte": "Gül gonce-i ümîd gibi gel açıl ey gül\nGül gül güzelim sen güle gülmek yaraşır gül\nGül handene nisbetle kalır hîç gül ü sünbül\nGül gül güzelim sen güle gülmek yaraşır gül\n\nİsmin gibi cismin de letâfetle müzeyyen\nAşkım gibi parlak yüzün ey mihr-i melek ten\nBen aşkın ile ağlamadan lezzet alırken\nGül gül güzelim sen güle gülmek yaraşır gül" },
            { "id": 11, "eser": "Gülsitâne eyleyip tercîh bir vîrâneyi", "makam": "Şevkefzâ", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Vals", "form": "Şarkı", "nota": "notalar/Gülsitâne-eyleyip-tercîh.pdf", "icrâ": "", "güfte": "Gülsitâne eyleyip tercîh bir vîrâneyi\nHasretinle mesken ettim kendime meyhâneyi\nYâr-i gâr etti felek destimdeki peymâneyi\nEyledin teşrîf ile ihyâ dil-i dîvâneyi" },
            { "id": 12, "eser": "Hâtır-ı nâşâdı gel gör bir nefes şâd et beni", "makam": "Segâh", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Ağır aksak", "form": "Şarkı", "nota": "notalar/Hâtır-ı-nâşâdı-gel.pdf", "icrâ": "https://youtu.be/iyaAJ7eYIR8?si=JbEKaFS2ugBSlALT", "güfte": "Hâtır-ı nâşâdı gel gör bir nefes şâd et beni\nKayd-ı hicrândan a zâlim artık âzâd et beni\nHasretinle pek harâbım bârî âbâd et beni\nKayd-ı hicrândan a zâlim artık âzâd et beni\nEy cefâ-cû eyle insâf âşık-ı bîçârene\nMerhem-i lutfunla imdât eyle gel âvârene\nKayd-ı hicrândan a zâlim artık âzâd et beni" },
            { "id": 13, "eser": "Hep sâye-i vaslında gönül şâd olacakken", "makam": "Hicaz", "güftekâr": "Tanbûrî Cemil Bey", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Sengin semâî", "form": "Şarkı", "nota": "notalar/Hep-sâye-i-vaslında.pdf", "icrâ": "https://youtu.be/2i0sur3mwAM?si=nA_8OUGM3_rMfUNo", "güfte": "Hep sâye-i vaslında gönül şâd olacakken\nKimdir ayıran âh efendim seni benden\nYıllarca bu hicrâna tahammül edemem ben\nKimdir ayıran âh efendim seni benden" },
            { "id": 14, "eser": "Hicrinle füzûn olmada ahzân-ı mezâlim", "makam": "Kürdîli-hicâzkâr", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "notalar/Hicrinle-füzûn-olmada.pdf", "icrâ": "https://youtu.be/6aUZ_UQhZZI?si=FqDZQhWJ8AiQeWu8", "güfte": "Hicrinle füzûn olmada ahzân-ı mezâlim\n Cânım beni âteşlere sen yaktın a zâlim\nGittikçe perîşân oluyor hüzn ile hâlim\n Cânım beni âteşlere sen yaktın a zâlim" },
            { "id": 15, "eser": "Longa", "makam": "Nikriz", "güftekâr": "Yok", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Nîm-sofyan", "form": "Longa", "nota": "notalar/Longa.pdf", "icrâ": "https://youtu.be/K-gcz9YuLHI?si=MtY5wBG8QKHj2r69", "güfte": "Yok" },
            { "id": 16, "eser": "Longa", "makam": "Nikriz", "güftekâr": "Yok", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Nîm-sofyan", "form": "Longa", "nota": "notalar/Longa2.pdf", "icrâ": "https://youtu.be/ZbcvhnC1BC0?si=AojuWV2P3ADUPvyF", "güfte": "Yok" },
            { "id": 17, "eser": "Mâtemzedeyim külbe-i ahzânımı gel gör", "makam": "Hicaz", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "notalar/Mâtemzedeyim-külbe-i-ahzânımı.pdf", "icrâ": "https://youtu.be/3E4EEFQxULw?si=BJ5B81cKDOTSGNFq", "güfte": "Mâtemzedeyim külbe-i ahzânımı gel gör\nEy çeşm-i semâvî dil-i giryânımı gel gör\nYâdınla dolan dîde-i hicrânımı gel gör\nEy çeşm-i semâvî dil-i giryânımı gel gör" },
            { "id": 18, "eser": "Nazîrin yok senin ey mâh yerde", "makam": "Evc", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak semâî", "form": "Şarkı", "nota": "notalar/Nazîrin-yok-senin.pdf", "icrâ": "https://youtu.be/eZelWc9X-gc?si=sfU8FvQtIf6nINuQ", "güfte": "Nazîrin yok senin ey mâh yerde\nArar gönlüm seni seyyârelerde\nBakar bîçâre her şeb âh eder de\nArar gönlüm seni seyyârelerde" },
            { "id": 19, "eser": "Nihândır dîdeden gerçi cemâlin", "makam": "Müstear", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Yürük semâî", "form": "Şarkı", "nota": "notalar/Nihândır-dideden-gerçi.pdf", "icrâ": "https://youtu.be/Dgqb5mR5Q6s?si=FISOyVmRDo44sT4e", "güfte": "Nihândır dîdeden gerçi cemâlin\nGözümden gitmiyor aslâ hayâlin\nMüyesser olmadı bir dem visâlin\nGözümden gitmiyor aslâ hayâlin\n\nNeden bu çektiğim senden vefâsız\nBana göstermedin bir gün cefâsız\nGeçip gitmekte ömrüm hep sefâsız\nGözümden gitmiyor aslâ hayâlin" },
            { "id": 20, "eser": "Peşrev", "makam": "Ferahfezâ", "güftekâr": "Yok", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Muhammes", "form": "Peşrev", "nota": "notalar/Peşrev.pdf", "icrâ": "https://youtu.be/RECWm_nbzzU", "güfte": "Yok" },
            { "id": 21, "eser": "Peşrev", "makam": "Hicâzkâr", "güftekâr": "Yok", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Muhammes", "form": "Peşrev", "nota": "notalar/Peşrev2.pdf", "icrâ": "https://youtu.be/2DQ5_qRc5ZY?si=RJqAJUMwR4k8cOEy", "baslangic": 31, "bitis": 203, "güfte": "Yok" },
            { "id": 22, "eser": "Peşrev", "makam": "Isfahan", "güftekâr": "Yok", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Devr-i kebir", "form": "Peşrev", "nota": "notalar/Peşrev3.pdf", "icrâ": "https://youtu.be/2DQ5_qRc5ZY?si=RJqAJUMwR4k8cOEy", "bitis": 92, "güfte": "Yok" },


            { "id": 13, "eser": "Taksim", "makam": "Hicaz", "güftekâr": "Yok", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Serbest", "form": "Taksim", "nota": "notalar/Taksim.pdf", "icrâ": "https://youtu.be/qJYdxRSjCQY?si=9L-lo9hOt3qmD4qH", "güfte": "Yok" },
            { "id": 13, "eser": "Taksim", "makam": "Pesendîde", "güftekâr": "Yok", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Serbest", "form": "Taksim", "nota": "notalar/Taksim2.pdf", "icrâ": "https://youtu.be/R2EleL6qNB4?si=QtAfFNa3Chjy1pkE", "güfte": "Yok" },


            { "id": 1, "eser": "Beni bîgâne-i hâb etti keder", "makam": "Sûznâk", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "notalar/beni_bigane.pdf", "icrâ": "https://youtu.be/h8e5R6--XjU?si=Kb_6-KZ21uKwsHBh", "güfte": "Beni bîgâne-i hâb etti keder\nDüşünür âh ederim tâ-be-seher\nArtırır derdimi muzlim geceler\nDüşünür âh ederim tâ-be-seher\n\nFirkat-i yâr ile kaldım nâçâr\nOldu bin dert ile gönül bîmâr\nEtti gam hâtırımı pek âzâr\nDüşünür âh ederim tâ-be-seher" },
            { "id": 1, "eser": "Beni bîgâne-i hâb etti keder", "makam": "Sûznâk", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Aksak", "form": "Şarkı", "nota": "notalar/beni_bigane.pdf", "icrâ": "https://youtu.be/h8e5R6--XjU?si=Kb_6-KZ21uKwsHBh", "güfte": "Beni bîgâne-i hâb etti keder\nDüşünür âh ederim tâ-be-seher\nArtırır derdimi muzlim geceler\nDüşünür âh ederim tâ-be-seher\n\nFirkat-i yâr ile kaldım nâçâr\nOldu bin dert ile gönül bîmâr\nEtti gam hâtırımı pek âzâr\nDüşünür âh ederim tâ-be-seher" },
            { "id": 8, "eser": "Pür-lerze olur rûyini gördükçe cenânım", "makam": "Muhayyer", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Sengin semâî", "form": "Şarkı", "nota": "", "icrâ": "", "sozler": "Pür-lerze olur..." },
            { "id": 9, "eser": "Sen gül eğlen şâd-mân ol", "makam": "Mâhur", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Ağır aksak", "form": "Şarkı", "nota": "", "icrâ": "", "sozler": "Sen gül eğlen..." },
            { "id": 10, "eser": "Sevdim seni ey işve-bâz", "makam": "Nihâvend", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Semâî", "form": "Şarkı", "nota": "", "icrâ": "", "sozler": "Sevdim seni..." },
            { "id": 11, "eser": "Taksim", "makam": "Hicaz", "güftekâr": "Yok", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Serbest", "form": "Taksim", "nota": "notalar/Taksim.pdf", "icrâ": "https://youtu.be/h8e5R6--XjU?si=Kb_6-KZ21uKwsHBh", "güfte": "Yok" },
            { "id": 11, "eser": "Var iken zâtında böyle hüsn ü ân olma nihân", "makam": "Mâhur", "güftekâr": "Mechul", "bestekâr": "Tanbûrî Cemil Bey", "usûl": "Ağır aksak", "form": "Şarkı", "nota": "", "icrâ": "", "sozler": "Var iken zâtında..." }
        ]
