const eserler = [
            { "id": 1, "eser": "A zâlim kanıma girdin", "makam": "Hisar", "güftekâr": "Mechul", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Aksak", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/A-zâlim-kanıma.pdf", "icrâ": "https://youtu.be/sprvnH6i1iA?si=rjDmNauH0iJWTL8n", "güfte": "A zâlim kanıma girdin\nYaktın beni harâb ettin\nŞuuruma halel verdin\nYaktın beni harâb ettin"},
            { "id": 2, "eser": "Açıl açıl gel efendim cihân behâr olsun ", "makam": "Hicâz-bûselik", "güftekâr": "Mechul", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Yürük semâî", "form": "Yürük semâî", "nota": "hamamizade-ismail-dede-efendi/notalar/Açıl-açıl-gel.pdf", "icrâ": "https://youtu.be/wQVgVqolx9E?si=heEfAn4IYZnpalFT", "güfte": "Açıl açıl gel efendim cihân behâr olsun\nSalın salın ki çemen seyr-i lâlezâr olsun\nTerahhum eyle aman hâlime benim mâhım\nSakın sakın ki yeter kârım âh ü zâr olsun"},
            { "id": 3, "eser": "Açıldı lâle-izârın dâğ-ı derûn", "makam": "Şehnaz", "güftekâr": "Mechul", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Zencir", "form": "Beste", "nota": "hamamizade-ismail-dede-efendi/notalar/Açıldı-lâle-izârın-ciğerde.pdf", "icrâ": "", "güfte": "Açıldı lâle-izârın dâğ-ı derûn\nMisâl-i şebnem akıttım gammınla girye-i hûn\nGönül ki beste-i zencîr-i zülfün ey şehnâz\nKalırsa başta bu sevdâ eder mi terk-i hümûm"},
            { "id": 4, "eser": "Ağlar inler pâyine yüzler sürer gönlüm gözüm", "makam": "Evc-bûselik", "güftekâr": "Dânişî", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Ağır çenber", "form": "Beste", "nota": "hamamizade-ismail-dede-efendi/notalar/Ağlar-inler-pâyine.pdf", "icrâ": "https://youtu.be/9np9E18mlyk?si=f0OQ4DGQsvtoKzfp", "baslangic": 172, "bitis": 623, "güfte": "Ağlar inler pâyine yüzler sürer gönlüm gözüm\nHâk-i pâye âh ü eşkin arz eder gönlüm gözüm\n\nBen nice nâlân ü giryân olmayam ey Dânişî\nMâcerâ-yı râz-ı aşkı fâş eder gönlüm gözüm"},
            { "id": 5, "eser": "Ağlatırlar güldürürler çeşmim yaşın sildirirler ", "makam": "Uşşak", "güftekâr": "Hamâmîzâde İsmâil Dede Efendi", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Aksak", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/Ağlatırlar-güldürürler-çeşmim.pdf", "icrâ": "https://youtu.be/4fmWgkLMfzA?si=1F9nPAjBISYtGORB", "güfte": "Ağlatırlar güldürürler\nÇeşmim yaşın sildirirler\nBunlar adam öldürürler\nKimler kimler kara gözlüler\n\nŞirin sözlüler güzeller\nGönül evine girerler\nÂşıkın aklın alırlar da\nYüze gülerler"},
            { "id": 6, "eser": "Ağlatma beni incitme aman", "makam": "Bayatî", "güftekâr": "Mechul", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Aksak semâî", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/Ağlatma-beni-incitme.pdf", "icrâ": "https://youtu.be/oF2CbNrWfJI?si=qpOLt_PT66lz2Pop", "güfte": "Ağlatma beni incitme aman\nDîvâne dilin hâl oldu yaman\nNittim sana ben ey kaşı kemân\nBöyle cefânın yoktur safâsı\n\nAşkınla yanar bu cism ile cân\nHîç merhametin yok mu a civân\nBülbül gibi dil etmekte figân\nBöyle cefânın yoktur safâsı"},
            { "id": 7, "eser": "Âh eylediğim sevr-i hırâmânın içindir", "makam": "Isfahan", "güftekâr": "Fuzûlî", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Yürük semâî", "form": "Yürük semâî", "nota": "hamamizade-ismail-dede-efendi/notalar/Âh-eylediğim-serv-i.pdf", "icrâ": "https://youtu.be/q4kJ-1WdAgM?si=kDnLMLW8yvl_Mo3O", "güfte": "Âh eylediğim sevr-i hırâmânın içindir\nKan ağladığım nergis-i mestânın içindür\n\nSerkeşteliğim kâkül-i müşkînin ucundan\nDîvâneliğim zülf-i perîşânın içindir"},
            { "id": 8, "eser": "Aklın alır aşıkların deleyler", "makam": "Beyati Araban", "güftekâr": "Mechul", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Aksak", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/", "icrâ": "", "güfte": ""},
            { "id": 9, "eser": "Aman felek ömrüm felek", "makam": "Uşşak", "güftekâr": "Mechul", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Aksak", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/", "icrâ": "", "güfte": ""},
            { "id": 10, "eser": "Arz-ı halim benim lutf-i dilbere kalsın", "makam": "Beyati Araban", "güftekâr": "Mechul", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Ağır Düyek", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/", "icrâ": "", "güfte": ""},
        ]
