const eserler = [
            { "id": 1, "eser": "A zâlim kanıma girdin", "makam": "Hisar", "güftekâr": "Mechul", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Aksak", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/A-zâlim-kanıma.pdf", "icrâ": "https://youtu.be/sprvnH6i1iA?si=rjDmNauH0iJWTL8n", "güfte": "A zâlim kanıma girdin\nYaktın beni harâb ettin\nŞuuruma halel verdin\nYaktın beni harâb ettin"},
            { "id": 2, "eser": "Açıl açıl gel efendim cihân behâr olsun ", "makam": "Hicâz-bûselik", "güftekâr": "Mechul", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Yürük semâî", "form": "Yürük semâî", "nota": "hamamizade-ismail-dede-efendi/notalar/Açıl-açıl-gel.pdf", "icrâ": "https://youtu.be/wQVgVqolx9E?si=heEfAn4IYZnpalFT", "güfte": "Açıl açıl gel efendim cihân behâr olsun\nSalın salın ki çemen seyr-i lâlezâr olsun\nTerahhum eyle aman hâlime benim mâhım\nSakın sakın ki yeter kârım âh ü zâr olsun"},
            { "id": 3, "eser": "Açıldı lâle-izârın dâğ-ı derûn", "makam": "Şehnaz", "güftekâr": "Mechul", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Zencir", "form": "Beste", "nota": "hamamizade-ismail-dede-efendi/notalar/Açıldı-lâle-izârın-ciğerde.pdf", "icrâ": "", "güfte": "Açıldı lâle-izârın dâğ-ı derûn\nMisâl-i şebnem akıttım gammınla girye-i hûn\nGönül ki beste-i zencîr-i zülfün ey şehnâz\nKalırsa başta bu sevdâ eder mi terk-i hümûm"},
            { "id": 4, "eser": "Ağlar inler pâyine yüzler sürer gönlüm gözüm", "makam": "Evc-bûselik", "güftekâr": "Dânişî", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Ağır çenber", "form": "Beste", "nota": "hamamizade-ismail-dede-efendi/notalar/Ağlar-inler-pâyine.pdf", "icrâ": "https://youtu.be/9np9E18mlyk?si=f0OQ4DGQsvtoKzfp", "baslangic": 172, "bitis": 623, "güfte": "Ağlar inler pâyine yüzler sürer gönlüm gözüm\nHâk-i pâye âh ü eşkin arz eder gönlüm gözüm\n\nBen nice nâlân ü giryân olmayam ey Dânişî\nMâcerâ-yı râz-ı aşkı fâş eder gönlüm gözüm"},
            { "id": 5, "eser": "Ağlatırlar güldürürler çeşmim yaşın sildirirler ", "makam": "Uşşak", "güftekâr": "Hamâmîzâde İsmâil Dede Efendi", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Aksak", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/Ağlatırlar-güldürürler-çeşmim.pdf", "icrâ": "https://youtu.be/4fmWgkLMfzA?si=1F9nPAjBISYtGORB", "güfte": "Ağlatırlar güldürürler\nÇeşmim yaşın sildirirler\nBunlar adam öldürürler\nKimler kimler kara gözlüler\n\nŞirin sözlüler güzeller\nGönül evine girerler\nÂşıkın aklın alırlar da\nYüze gülerler"},
            { "id": 6, "eser": "Ağlatma beni incitme aman", "makam": "Bayatî", "güftekâr": "Mechul", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Aksak semâî", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/Ağlatma-beni-incitme.pdf", "icrâ": "https://youtu.be/oF2CbNrWfJI?si=qpOLt_PT66lz2Pop", "güfte": "Ağlatma beni incitme aman\nDîvâne dilin hâl oldu yaman\nNittim sana ben ey kaşı kemân\nBöyle cefânın yoktur safâsı\n\nAşkınla yanar bu cism ile cân\nHîç merhametin yok mu a civân\nBülbül gibi dil etmekte figân\nBöyle cefânın yoktur safâsı"},
            { "id": 7, "eser": "Âh eylediğim sevr-i hırâmânın içindir", "makam": "Isfahan", "güftekâr": "Fuzûlî", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Yürük semâî", "form": "Yürük semâî", "nota": "hamamizade-ismail-dede-efendi/notalar/Âh-eylediğim-serv-i.pdf", "icrâ": "https://youtu.be/q4kJ-1WdAgM?si=kDnLMLW8yvl_Mo3O", "güfte": "Âh eylediğim sevr-i hırâmânın içindir\nKan ağladığım nergis-i mestânın içindür\n\nSerkeşteliğim kâkül-i müşkînin ucundan\nDîvâneliğim zülf-i perîşânın içindir"},
            { "id": 8, "eser": "Aman felek ömrüm felek", "makam": "Uşşak", "güftekâr": "Mechul", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Aksak", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/Aman-felek-ömrüm.pdf", "icrâ": "https://youtu.be/veD4uF35Tx4?si=mHDZbBbuGiTGqtlT", "güfte": "Aman felek ömrüm felek\nNiyâzım var geçmez dilek\nAslı hûrî soyu melek\nYârim etme edâların\nO demlerin keremlerin\nYârim etme edâların\n\nBir oyunbaz Gürcü kızı\nTopukta şalvar kırmızı\nÂteşlere yakma bizi\nYârim etme edâların\nO demlerin keremlerin\nYârim etme edâların"},
            { "id": 9, "eser": "Arz-ı hâlim benim lutf-i dilbere kalsın", "makam": "Bayatî-arabân", "güftekâr": "Mechul", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Ağır düyek", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/Arz-ı-hâlim-benim.pdf", "icrâ": "", "güfte": "Arz-ı hâlim benim lûtf-i dilbere kalsın\nCismimdeki yara hançere kalsın\nDerd-i şerh-i hâlim vakt-i âhare kalsın\nBenim hâl-i dilim mahşere kalsın"},
            { "id": 10, "eser": "Âşık olalı sen yâre gönül", "makam": "Isfahan", "güftekâr": "Hamâmîzâde İsmâil Dede Efendi", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Aksak", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/Âşık-olalı-sen.pdf", "icrâ": "", "güfte": "Âşık olalı sen yâre gönül\nYanmakta yürek pür-yâre gönül\nTek etme fedâ sen bu kulunu\nRâzî oluyor âzâre gönül\nUslanmayacak hîç çâresi yok\nAldanmayacak hîç çâresi yok\nDîvâne gönül bîçâre gönül"},
            { "id": 11, "eser": "Âşinâ-yı aşk olandan âh ü zâr eksik değil", "makam": "Hicaz", "güftekâr": "Niyâzî-i Mısrî", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Serbest", "form": "Durak", "nota": "hamamizade-ismail-dede-efendi/notalar/Âşinâ-yı-aşk-olandan.pdf", "icrâ": "https://youtu.be/1l67xfkZZgc?si=uEc1hFC-yKhBug0r", "baslangic": 131,"güfte": "Âşinâ-yı aşk olandan âh ü zâr eksik değil\nKeştî‐i bahre demâdem rûzigâr eksik değil\nŞem'‐i aşka Mısrîyâ yandır özün yoğ ol müdâm\nÂşıka her yokluğun üstünde var eksik değil"},
            { "id": 12, "eser": "Aşk-ı tû nihâl-i hayret âmed", "makam": "Rast-ı cedid", "güftekâr": "Hâfız-ı Şîrâzî", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi - Reis Mahmûd Efendi", "usûl": "Hafif", "form": "Kâr", "nota": "hamamizade-ismail-dede-efendi/notalar/Aşk-ı-tû-nihâl-i.pdf", "icrâ": "https://youtu.be/YBjFL8qUBC8?si=or4t8jRqeiktcaBn", "güfte": "Aşk-ı tû nihâl-i hayret âmed\nVasl-i tû kemâl-i hayret âmed\n\nBes garka-i hâl-i vasl kâher\nHem ber ser-i hâl-i hayret âmed\n\nYek dil binümâ ki der reh-i ô\nBer çihre ne hâl-i hayret âmed\n\nNe vasl bimâned u ne vâsıl\nÂn câ ki hayâl-i hayret âmed\n\nEz her tarafî ki gûş kerdem\nÂvâz-i suâl-i hayret âmed\n\nŞud münhezim ez kemâl-i izzet\nÂn râ ki celâl-i hayret âmed\n\nSer-tâ-kadem-i vücûd-i Hâfız\nDer aşk-ı nihâl-i hayret âmed"},
            { "id": 13, "eser": "Aşkınla ben ey nâzenîn", "makam": "Hicaz", "güftekâr": "Mechul", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Düyek", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/Aşkınla-ben-ey.pdf", "icrâ": "https://youtu.be/dJFw8v3ENDY?si=4Wh6uUWD2Zck_WjD", "baslangic": 185, "güfte": "Aşkınla ben ey nâzenîn\nMecbûrunam mecbûrunam\nEy serv-i kâmet nev-zemîn\nMecbûrunam mecbûrunam\n\nGeldim kapına bendenem\nHem bende-i efgendenem\nRahmeyle gel nâlendenem\nMecbûrunam mecbûrunam"},
            { "id": 14, "eser": "Âteş nezened der dil-i mâ illâ hû", "makam": "Sabâ-bûselik", "güftekâr": "Mevlânâ Celâleddîn-i Rûmî", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Düyek", "form": "Mevlevî âyîni", "nota": "hamamizade-ismail-dede-efendi/notalar/Âteş-nezened-der.pdf", "icrâ": "https://youtu.be/g2FAJp5Y74w?si=q8hU2bX_qVDvT_Pl", "güfte": "Âteş nezened der dil-i mâ illâ hû\nKûteh neküned menzil-i mâ illâ hû\n\nGer âlemiyân cümle tabîbân bâşend\nHallî neküned müşkil-i mâ illâ hû\n\nHey hey ne acâib bezemiş hüsn ile Bârî\nBu sûret-i yârı, bu nakş u nigârı\nHer ehl-i nazar kim göre tahsîn ola kârı\nBu çeşm ü izârı, kalmaya karârı\n\nUşşâkı katar eyledi aşk içre Muhammed\nOl şâh-ı mümecced, ol matlab u maksad\nEy üştür-i dil sen olagör pîş-i katârî\nÇek aşk ile bârı, bî-verd ile hârı\n\nBen bilmez idim gizli ayân hep sen imişsin\nTenlerde vü cânlarda nihân hep sen imişsin\n\nSenden bu cihân içre nişân ister idim ben\nÂhir bunu bildim ki cihân hep sen imişsin\n\nEy şâh-ı şehr-i akl ü cân ber taht-ı dil hâkân tüyî\nEnder zemîn ü âsumân sultân-ı sultânân tüyî\n\nDer cân-i mâ cânân tüyî der kân-i mâ nî kan tüyî\nCennet tüyî şerbet tüyî sâkî tüyî rıdvân tüyî\nBâ âşık ez-dünyâ me-gû v’ez milket-i ukbâ me-gû\nCüz hasret-i Mevlâ me-gû mî gû ki în ü an tüyî\n\nÂşıkân der kûy-i cânân es-salâ\nSûy-i an hurşîd-i tâbân es-salâ\n\nŞems-i Tebrîzî zi bâlâ-yi felek\nHer zamânî mî keşed hân es-salâ\n\nEy ki hezâr âferîn bu nice sultân olur\nKulu olan kişiler hüsrev ü hâkân olur\n\nHer ki bugün Veled’e inanuben yüz süre\nYoksul ise bay olur bay ise sultân olur\n\nDer bâğ-ı cemâlî sanemâ çün gül-i ra‘nâ\nDer çeşm çü nûrî vü çü cân der heme a‘zâ\n\nMen bülbül-i gülzârem ü der dâm-i tü zârem\nEz çîst aceb bâ tü me-râ in heme sevdâ\n\nEy rûy-i tû kıble-i cihân ü dil-i men\nV’an der dü cihân emn ü emân-i dil-i men\nHem cân ü tenî vü hem tû cân-i dil-i men\nEy gevher-i deryâ-yi nihân-i dil-i men\n\nTü mâhî acîbî ki mislî ne-dârî\nBe her cilve cânâ der âteş sipârî\n\nBe zülfeyn ü ebrû be çeşmân-i âhû\nPey-i dilrübâyî çü şîr-i şikârî\n\nMeh ü hur gulâmet zi cân geşt râmet\nDü âlem be dâmet çi zîbâ nigârî\n\nNazîret ne-dîdem ne ez kes şinîdem\nDil ü dîn bi-bürdî çi ayyâr yârî\n\nVeled râ çi bâşed şehâ ger zi rahmet\nZi silk-i gulâmân-i hîşet şümârî\n\nSultân-ı menî sultân-ı menî\nEnder dil ü cân îmân-ı menî\n\nDer men bi-demî men zinde şevem\nYek cân çi şeved sad cân-ı menî"},
            { "id": 15, "eser": "Ayağı tozunu sürme çekelden gözüme cânım", "makam": "Sûz-i dil", "güftekâr": "Niyâzî-i Mısrî", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Durak evferi", "form": "Durak", "nota": "hamamizade-ismail-dede-efendi/notalar/Ayağı-tozunu-sürme.pdf", "icrâ": "https://youtu.be/ZdxzqiuaayI?si=doj1Sfr-jKmNmcF2", "güfte": "Ayağı tozunu sürme çekelden gözüme cânım\nGörünür oldu her gâhî gözüme vech-i cânânım\n\nBuluştu bir ten ü bir cân bu mülkü ettiler seyrân\nNiyâzî'den görünen ol ben ancak ad ile sânım"},
            { "id": 16, "eser": "Aybeder hâl-i dil-i âşüfte-sâmânım gören", "makam": "Evc-bûselik", "güftekâr": "Abdülbâki Ârif Efendi", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Muhammes", "form": "Beste", "nota": "hamamizade-ismail-dede-efendi/notalar/Aybeder-hâl-i-dil-i.pdf", "icrâ": "https://youtu.be/9np9E18mlyk?si=IS99LUsrur7Myh65", "baslangic": 624, "bitis": 793, "güfte": "Aybeder hâl-i dil-i âşüfte-sâmânım gören\nGörmeden ol şûhu etvâr-ı perîşânım gören\n\nOlmamak mümkün mü üftâde o nahl-i işveye\nHâk-i râh olmaz mı ol serv-i hırâmânım gören"},
            { "id": 17, "eser": "Bağrımdaki biten başlar Muhammed'in aşkındandır", "makam": "Hüzzam", "güftekâr": "Seyyid Nizamoğlu", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Düyek", "form": "İlâhî", "nota": "hamamizade-ismail-dede-efendi/notalar/Bağrımdaki-biten-başlar.pdf", "icrâ": "https://youtu.be/rqkrxwzJwGA?si=GlW0oZyCdFoDtJAH", "güfte": "Bağrımdaki biten başlar\nMuhammed'in aşkındandır\nGözlerimden akan yaşlar\nMuhammed'in aşkındandır\n\nHer sabâh akşam yandığım\nÂlemlerden usandığım\nÇarh urup semâ döndüğüm\nMuhammed'in aşkındandır\n\nCiğerim dağladıklarım\nSu gibi çağladıklarım\n Her seher ağladıklarım\nMuhammed'in aşkındandır\n\nDahledenler devrânıma\nErmediler seyrânıma\nKıydığım kendi cânıma\nMuhammed'in aşkındandır\n\nGörün Seyfullâh'ın kasdın\nSever ol Allâh'ın dostun\nSorarlarsa niçin mestsin\nMuhammed'in aşkındandır" },
            { "id": 18, "eser": "Bahârın zamânı geldi a cânım", "makam": "Hicaz", "güftekâr": "Mechul", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Aksak", "form": "Köçekçe", "nota": "hamamizade-ismail-dede-efendi/notalar/Bahârın-zamânı-geldi.pdf", "icrâ": "https://youtu.be/QRu-3nvRq7s?si=Ujs62m5YoiVtVosC", "baslangic": 559, "güfte": "Bahârın zamânı geldi\nYavru ceylân gel gidelim\nYollarımız yeşillendi\nYavru ceylân gel gidelim\n\nKolların boynuma uzat\nZülfünün tellerin düzelt\nAvcıların yolun gözet\nYavru ceylân gel gidelim" },
            { "id": 20, "eser": "Bana gayrı karışma barış ister barışma", "makam": "Saba", "güftekâr": "Belirsiz", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Aksak", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/", "icrâ": "https://youtu.be/8wptqonLd7Q?si=DVMkts9ecAL6P0wn", "güfte": "Bana gayrı karışma\nBarış ister barışma\nGönüldür bu yarışma\nBarış ister barışma\nİsterim istemem\nBarış ister barışma\n\nAman ey nevcivânım\nKerem et yakma cânım\nMuhayyersin a cânım\nBarış ister barışma\nİsterim istemem\nBarış ister barışma" },
            
            { "id": 21, "eser": "Beğendim seni efendim geçmem aslâ ben", "makam": "Ferahnak", "güftekâr": "Belirsiz", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Düyek", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/", "icrâ": "", "güfte": "Beğendim seni efendim geçmem aslâ ben\nSeni sevdim seveli çekmediğim kalmadı zâra ben" },
            
            { "id": 22, "eser": "Ben bendesiyim bendesiyim", "makam": "Tarz-ı Cedid", "güftekâr": "Belirsiz", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Aksak Semai", "form": "Ağır Semai", "nota": "hamamizade-ismail-dede-efendi/notalar/", "icrâ": "", "güfte": "" },
            
            { "id": 23, "eser": "Ben bilmedim bana n'oldu", "makam": "Hicaz", "güftekâr": "Belirsiz", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Ağır Düyek", "form": "Şarkı", "nota": "", "icrâ": "hamamizade-ismail-dede-efendi/notalar/", "güfte": "Ben bilmedim bana noldu\nGül benzim sarardı soldu\nHasretinle kalbim doldu\nRahm eyle bana ey peri" },
            
            { "id": 24, "eser": "Ben bilmez idim gizli ayân hep sen imişsin", "makam": "Suzinak", "güftekâr": "Ahmet Dede (Köse)", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Sofyan", "form": "İlahi", "nota": "hamamizade-ismail-dede-efendi/notalar/", "icrâ": "", "güfte": "Ben bilmez idim gizli ayân hep sen imişsin\nTenlerde cân u dillerde sühan hep sen imişsin" },
            
            { "id": 25, "eser": "Ben mübtelâ oldum sana", "makam": "Şehnaz Buselik", "güftekâr": "Belirsiz", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Aksak", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/", "icrâ": "", "güfte": "" },
            
            { "id": 26, "eser": "Ben mübtelâ olsam sana", "makam": "Ferahnak", "güftekâr": "Belirsiz", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Aksak", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/", "icrâ": "", "güfte": "" },
            
            { "id": 27, "eser": "Ben sana âşık değilim", "makam": "Muhayyer", "güftekâr": "Belirsiz", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Yürük Semai", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/", "icrâ": "", "güfte": "" },
            
            { "id": 28, "eser": "Ben seni sevdim seveli kaynayıp coştum", "makam": "Bestenigar", "güftekâr": "Hamâmîzâde İsmâil Dede Efendi", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Curcuna", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/", "icrâ": "", "güfte": "Ben seni sevdim seveli kaynayıp coştum\nAklımı başımdan alıp deryâya düştüm" },
            
            { "id": 29, "eser": "Ben yürürüm yâne yâne aşk boyadı beni kâne", "makam": "Arazbar", "güftekâr": "Yunus Emre", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Düyek", "form": "İlahi", "nota": "hamamizade-ismail-dede-efendi/notalar/", "icrâ": "", "güfte": "Ben yürürüm yâne yâne\nAşk boyadı beni kâne\nNe âkilem ne dîvâne\nGel gör beni aşk neyledi" },
            
            { "id": 30, "eser": "Bend oldu dil bir şûh-i cihâne", "makam": "Nühüft", "güftekâr": "Leyla Hanım", "bestekâr": "Hamâmîzâde İsmâil Dede Efendi", "usûl": "Aksak Semai", "form": "Şarkı", "nota": "hamamizade-ismail-dede-efendi/notalar/", "icrâ": "", "güfte": "Bend oldu dil bir şûh-i cihâne\nBakmaz mürüvvet eyler bahâne" }
        ]
